version: '3.9'

services:
  restaurant.api:
    image: ${DOCKER_REGISTRY-}restaurant
    container_name: restaurant.api
    build:
      context: .
      dockerfile: Restaurant/Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - restaurant
    depends_on:
      - restaurant.database
      - restaurant.cache
        
  restaurant.database:
    image: postgres:latest
    container_name: restaurant.database
    environment:
      - POSTGRES_DB=Restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=97425777Teo
    volumes:
      - ./.containers/restaurant-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - restaurant
        
  restaurant.cache:
    image: redis:latest
    container_name: restaurant.cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - restaurant

networks:
  restaurant:
    driver: bridge